workflows:
  ios-distribute:
    name: iOS Distribute (Manual Signing)
    integrations:
      app_store_connect: Codemagic-key
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "papricut.app.mobile"
        TEAM_ID: "H9A4H444G4"
        PROFILE_NAME: "Papricut_AppStore_2025"
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID 
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      groups:
        - Papricut
    triggering:
      events:
        - push
    scripts:
      - name: Install System Dependencies
        script: |
          brew install jq
          npm install -g @angular/cli @ionic/cli native-run cordova-res

      - name: Install Dependencies
        script: |
          # Clean slate
          rm -rf node_modules package-lock.json
          
          # Install exact versions
          npm install --legacy-peer-deps --no-audit
          npm install -g @angular/cli@17.3.17 @ionic/cli@7.2.1
          
          # Force update critical packages
          npx npm-force-resolutions
          
          # Verify installations
          ng version
          ionic info

      - name: Build Production Assets
        script: |
          # Clean previous builds
          rm -rf www
          
          # Build with production configuration
          npm run build -- --configuration production
          
          # Verify www directory
          if [ ! -d "www" ]; then
            echo "❌ Build failed - www directory not created"
            exit 1
          fi
          
          # Verify critical files
          REQUIRED_FILES=(
            "index.html"
            "main.js"
            "polyfills.js"
            "runtime.js"
            "styles.css"
          )
          
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "www/$file" ]; then
              echo "❌ Missing required file: www/$file"
              exit 1
            fi
          done

      - name: Sync Capacitor
        script: |
          npx cap sync ios --deployment
          
          # Verify iOS assets
          if [ ! -d "ios/App/App/public" ] && [ ! -d "ios/App/App/www" ]; then
            echo "❌ Capacitor sync failed - no web assets in iOS project"
            exit 1
          fi

      - name: Clean Build Environment
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf "$HOME/build"
          mkdir -p "$HOME/build"

      - name: Verify Angular Config
        script: |
          if ! jq -e '.projects.app.architect.build.configurations.production' angular.json >/dev/null; then
            echo "❌ Missing production build config in angular.json"
            exit 1
          fi

      - name: Build Ionic Project
        script: |
          # Clean environment
          rm -rf www node_modules/.cache .angular/cache
          
          # Set memory limits
          export NODE_OPTIONS="--max-old-space-size=4096"
          export NODE_ENV=production
          
          # Production build with verbose output
          echo "=== STARTING PRODUCTION BUILD ==="
          ionic build --prod --verbose -- --output-hashing=all --source-map --stats-json 2>&1 | tee build.log
          
          # Verify build output
          if [ ! -d "www" ]; then
            echo "❌ Build failed - www directory not created"
            grep -A 20 -B 20 -i "error" build.log || cat build.log
            exit 1
          fi
          
          # Verify critical files
          REQUIRED_FILES=(
            "index.html"
            "main.js"
            "polyfills.js"
            "runtime.js"
            "styles.css"
            "assets/"
          )
          
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -e "www/$file" ]; then
              echo "❌ Missing required file: www/$file"
              exit 1
            fi
          done

      - name: Prepare Native Assets
        script: |
          # Generate splash screens and icons
          cordova-res ios --skip-config --copy
          
          # Sync web assets to native project
          npx cap sync ios --deployment
          
          # Verify sync
          if [ ! -d "ios/App/App/public" ] && [ ! -d "ios/App/App/www" ]; then
            echo "❌ Capacitor sync failed - no web assets in native project"
            exit 1
          fi

      - name: Decode Signing Assets
        script: |
          echo "$DISTRIBUTION_CERTIFICATE" | base64 --decode > signing.p12
          echo "$PROVISIONING_PROFILE" | base64 --decode > "$PROFILE_NAME.mobileprovision"

      - name: Install Provisioning Profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -D -i "$PROFILE_NAME.mobileprovision"))
          cp "$PROFILE_NAME.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/"$PROFILE_UUID".mobileprovision
          echo "export PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Setup Code Signing
        script: |
          security create-keychain -p "" build.keychain
          security import signing.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -k "" build.keychain

      - name: Configure Pods Project
        script: |
          # Disable code signing for Pods
          /usr/libexec/PlistBuddy -c "Add :objects:13D8C11F2543F3D900D83B1E:buildSettings:CODE_SIGNING_ALLOWED string NO" ios/App/Pods/Pods.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Add :objects:13D8C11F2543F3D900D83B1E:buildSettings:CODE_SIGNING_REQUIRED string NO" ios/App/Pods/Pods.xcodeproj/project.pbxproj

      - name: Increment Build Number
        script: |
          PLIST_PATH="ios/App/App/Info.plist"
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
          NEW_BUILD=$((CURRENT_BUILD + 1))
          /usr/libexec/PlistBuddy -c "Set CFBundleVersion $NEW_BUILD" "$PLIST_PATH"
          echo "Updated build number from $CURRENT_BUILD to $NEW_BUILD"

      - name: Build IPA
        script: |
          export NSUnbufferedIO=YES
          
          echo "=== ARCHIVING APP ==="
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                    -scheme "$XCODE_SCHEME" \
                    -sdk iphoneos \
                    -configuration Release \
                    -archivePath "$HOME/build/App.xcarchive" \
                    -allowProvisioningUpdates \
                    -destination 'generic/platform=iOS' \
                    DEVELOPMENT_TEAM="$TEAM_ID" \
                    PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
                    CODE_SIGN_STYLE="Manual" \
                    CODE_SIGN_IDENTITY="iPhone Distribution" \
                    PROVISIONING_PROFILE="$PROFILE_UUID" \
                    OTHER_CODE_SIGN_FLAGS="--keychain build.keychain" \
                    ENABLE_BITCODE=NO \
                    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
                    archive | tee "$HOME/build/archive_log.txt"

          echo "=== EXPORTING IPA ==="
          xcodebuild -exportArchive \
                    -archivePath "$HOME/build/App.xcarchive" \
                    -exportPath "$HOME/build/ipa" \
                    -exportOptionsPlist ExportOptions.plist \
                    -allowProvisioningUpdates | tee "$HOME/build/export_log.txt"

      - name: Validate Bundle
        script: |
          APP_PATH="$HOME/build/App.xcarchive/Products/Applications/App.app"
          
          # Verify web assets
          if [ ! -d "$APP_PATH/www" ] && [ ! -d "$APP_PATH/public" ]; then
            echo "❌ Web assets missing from app bundle"
            find "$APP_PATH" -maxdepth 1
            exit 1
          fi
          
          # Verify plugins
          REQUIRED_PLUGINS=(
            "Capacitor.framework"
            "CapacitorCordova.framework"
            "CapacitorCamera.framework"
          )
          
          for plugin in "${REQUIRED_PLUGINS[@]}"; do
            if [ ! -d "$APP_PATH/Frameworks/$plugin" ]; then
              echo "❌ Missing plugin: $plugin"
              exit 1
            fi
          done
          
          # Verify splash screen
          if [ ! -f "$APP_PATH/Base.lproj/LaunchScreen.storyboardc" ]; then
            echo "❌ Missing compiled splash screen"
            exit 1
          fi

      - name: Final Checks
        script: |
          echo "=== BUILD VALIDATION ==="
          echo "App Version: $(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$HOME/build/App.xcarchive/Products/Applications/App.app/Info.plist")"
          echo "Web Assets: $(find "$HOME/build/App.xcarchive/Products/Applications/App.app/www" -type f | wc -l) files"
          echo "Plugins: $(find "$HOME/build/App.xcarchive/Products/Applications/App.app/Frameworks" -name "*.framework" | wc -l) frameworks"
          codesign -dv --verbose=4 "$HOME/build/App.xcarchive/Products/Applications/App.app"

    artifacts:
      - $HOME/build/ipa/*.ipa
      - $HOME/build/archive_log.txt
      - $HOME/build/export_log.txt
      - build.log
    publishing:
      app_store_connect:
        auth: integration
        api_key: Codemagic-key
        submit_to_testflight: true