workflows:
  ios-distribute:
    name: iOS Distribute (Manual Signing)
    integrations:
      app_store_connect: Codemagic-key
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "papricut.app.mobile"
        TEAM_ID: "H9A4H444G4"
        PROFILE_NAME: "Papricut_AppStore_2025"
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        DISTRIBUTION_CERTIFICATE: $DISTRIBUTION_CERTIFICATE
        PROVISIONING_PROFILE: $PROVISIONING_PROFILE
        CERTIFICATE_PASSWORD: $CERTIFICATE_PASSWORD
        NODE_OPTIONS: "--max-old-space-size=4096"
        NODE_VERSION: "18.x"
        NVM_DIR: "/Users/builder/.nvm"
      groups:
        - Papricut
    triggering:
      events:
        - push
    cache:
      cache_paths:
        - ~/.npm
        - node_modules
        - .angular/cache
    scripts:
      - name: Install and Use Node 18
        script: |
          echo "=== INSTALLING NODE 18 ==="
          # Install Node 18 using Codemagic's built-in tool
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
          node -v
          
          # Verify Node is actually 18.x
          if ! node -v | grep -q 'v18'; then
            echo "❌ Failed to set Node 18"
            exit 1
          fi
          
          # Install required global packages
          npm install -g npm@latest
          npm install -g @angular/cli@17.3.17 @ionic/cli@7.2.1 native-run cordova-res
          
          # Install correct CocoaPods version
          gem install cocoapods -v 1.16.2 --conservative
      - name: Set Up Environment
        script: |
          brew install jq
          npm install -g npm@latest
          npm install -g @angular/cli@17.3.17 @ionic/cli@7.2.1 native-run cordova-res
      - name: Install Dependencies
        script: |
          echo "=== CLEANING ENVIRONMENT ==="
          rm -rf node_modules .angular/cache
          npm cache clean --force
          
          echo "=== INSTALLING DEPENDENCIES ==="
          npm install --legacy-peer-deps --no-audit
          npm install --save-exact @angular-devkit/build-angular@17.3.17 @ionic/angular-toolkit@7.1.1
          
          echo "=== VERIFYING INSTALLATIONS ==="
          if [ ! -d "node_modules/@angular-devkit/build-angular" ]; then
            echo "❌ CRITICAL: Angular build tools missing!"
            npm list
            exit 1
          fi
      - name: Verify Capacitor Plugins
        script: |
          echo "=== CAPACITOR PLUGIN CHECK ==="
          # Check engine requirements
          grep -r "engine" node_modules/@capacitor/*/package.json | grep "node"
          
          # Verify core plugins exist
          REQUIRED_PLUGINS=(
            "@capacitor/core" 
            "@capacitor/ios"
            "@capacitor/camera"
            "@capacitor/keyboard"
          )
          
          for plugin in "${REQUIRED_PLUGINS[@]}"; do
            if [ ! -d "node_modules/$plugin" ]; then
              echo "❌ Missing plugin: $plugin"
              exit 1
            fi
          done
      - name: Verify Environment Files
        script: |
          if [ ! -f "src/environments/environment.ts" ] || [ ! -f "src/environments/environment.prod.ts" ]; then
            echo "❌ Missing environment files!"
            ls -la src/environments/
            exit 1
          fi
      - name: Build Angular App
        script: |
          echo "=== BUILDING PRODUCTION ASSETS ==="
          
          # First verify environment files
          if [ ! -f "src/environments/environment.prod.ts" ]; then
            echo "❌ Missing production environment file!"
            exit 1
          fi
          
          # Run build with verbose output
          ng build --configuration production --output-path www --verbose
          
          if [ ! -d "www" ]; then
            echo "❌ Build failed - www directory not created"
            echo "=== BUILD DEBUG OUTPUT ==="
            cat angular.log || echo "No angular.log found"
            exit 1
          fi
          
          # Verify critical files
          REQUIRED_FILES=(
            "www/index.html"
            "www/main.*.js"
            "www/runtime.*.js"
          )
          
          for file in "${REQUIRED_FILES[@]}"; do
            if ! ls $file >/dev/null 2>&1; then
              echo "❌ Missing web file: $file"
              ls -la www/
              exit 1
            fi
          done
      - name: Verify Web Assets
        script: |
          echo "=== WEB ASSET VALIDATION ==="
          
          # Check for main JS file (hashed version)
          if ! ls www/main.*.js >/dev/null 2>&1; then
            echo "❌ Main JS file missing"
            echo "Found files:"
            ls -la www/*.js
            exit 1
          fi
          
          # Check for runtime JS file (hashed version)
          if ! ls www/runtime.*.js >/dev/null 2>&1; then
            echo "❌ Runtime JS file missing"
            exit 1
          fi
          
          # Check for index.html
          if [ ! -f "www/index.html" ]; then
            echo "❌ Index.html missing"
            exit 1
          fi
          
          # Verify production API URL in any main JS file
          MAIN_JS_FILE=$(ls www/main.*.js)
          if ! grep -q "account.papricut.com" "$MAIN_JS_FILE"; then
            echo "❌ Production API URL not found in build"
            echo "Checking file: $MAIN_JS_FILE"
            echo "First 50 lines:"
            head -50 "$MAIN_JS_FILE" | grep -i -A5 -B5 "account" || echo "No account.papricut.com found"
            exit 1
          fi
          
          echo "✅ Web assets validated successfully"
      - name: Configure Podfile
        script: |
          echo "=== PODFILE VERIFICATION ==="
          if [ -f "ios/App/Podfile" ]; then
            echo "Existing Podfile detected - validating contents..."
            if ! grep -q "CapacitorCordova" "ios/App/Podfile"; then
              echo "❌ Podfile missing Capacitor plugins"
              exit 1
            fi
          else
            echo "Generating new Podfile..."
            # Your existing Podfile generation script
          fi
          
          echo "Running pod install..."
          cd ios/App && pod install --repo-update && cd ../..
          
          # Verify Pods were installed
          if [ ! -d "ios/App/Pods/Capacitor" ]; then
            echo "❌ Pod installation failed"
            exit 1
          fi
      - name: Verify iOS Platform
        script: |
          echo "=== IOS PLATFORM CHECK ==="
          if [ ! -d "ios/App" ]; then
            echo "Initializing iOS platform..."
            npx cap add ios
          fi
          
          # Critical iOS files check
          IOS_FILES=(
            "ios/App/App.xcodeproj/project.pbxproj"
            "ios/App/App/Info.plist"
          )
          
          for file in "${IOS_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing iOS file: $file"
              exit 1
            fi
          done
      - name: Sync Capacitor iOS Project
        script: |
          echo "=== SYNCING CAPACITOR IOS ==="
          # Ensure iOS directory exists
          if [ ! -d "ios/App" ]; then
            echo "❌ iOS directory missing - did the platform add fail?"
            exit 1
          fi
          
          # Full sync with verbose output
          npx cap sync ios --verbose
          
          # Verify critical files were created
          REQUIRED_FILES=(
            "ios/App/App/public/index.html"
            "ios/App/App/App.entitlements"
            "ios/App/Podfile"
          )
          
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing critical file: $file"
              echo "Directory contents:"
              find ios/App -type f
              exit 1
            fi
          done
          
          echo "=== POD INSTALL ==="
          cd ios/App && pod install --repo-update && cd ../..
          
          echo "=== VERIFYING SYNC ==="
          if ! grep -q "account.papricut.com" "ios/App/App/App.entitlements"; then
            echo "❌ App-bound domains not configured in entitlements"
            cat ios/App/App/App.entitlements
            exit 1
          fi

      - name: Update Info.plist
        script: |
          PLIST_PATH="ios/App/App/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :UILaunchStoryboardName LaunchScreen" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :UISupportedInterfaceOrientations:0 UIInterfaceOrientationPortrait" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSExceptionDomains:api.papricut.com dict" "$PLIST_PATH" || true
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:api.papricut.com:NSIncludesSubdomains bool true" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:api.papricut.com:NSExceptionAllowsInsecureHTTPLoads bool false" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:api.papricut.com:NSExceptionRequiresForwardSecrecy bool true" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:api.papricut.com:NSExceptionMinimumTLSVersion string TLSv1.2" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSExceptionDomains:cdn.papricut.com dict" "$PLIST_PATH" || true
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:cdn.papricut.com:NSIncludesSubdomains bool true" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:cdn.papricut.com:NSExceptionAllowsInsecureHTTPLoads bool false" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:cdn.papricut.com:NSExceptionRequiresForwardSecrecy bool true" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :NSAppTransportSecurity:NSExceptionDomains:cdn.papricut.com:NSExceptionMinimumTLSVersion string TLSv1.2" "$PLIST_PATH"

      - name: Clean Build Environment
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf "$HOME/build"
          mkdir -p "$HOME/build"

      - name: Decode Signing Assets
        script: |
          echo "$DISTRIBUTION_CERTIFICATE" | base64 --decode > signing.p12
          echo "$PROVISIONING_PROFILE" | base64 --decode > "$PROFILE_NAME.mobileprovision"

      - name: Install Provisioning Profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -D -i "$PROFILE_NAME.mobileprovision"))
          cp "$PROFILE_NAME.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/"$PROFILE_UUID".mobileprovision
          echo "export PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Setup Code Signing
        script: |
          security create-keychain -p "" build.keychain
          security import signing.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -k "" build.keychain

      - name: Configure Pods Project
        script: |
          /usr/libexec/PlistBuddy -c "Add :objects:13D8C11F2543F3D900D83B1E:buildSettings:CODE_SIGNING_ALLOWED string NO" ios/App/Pods/Pods.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Add :objects:13D8C11F2543F3D900D83B1E:buildSettings:CODE_SIGNING_REQUIRED string NO" ios/App/Pods/Pods.xcodeproj/project.pbxproj

      - name: Increment Build Number
        script: |
          PLIST_PATH="ios/App/App/Info.plist"
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
          NEW_BUILD=$((CURRENT_BUILD + 1))
          /usr/libexec/PlistBuddy -c "Set CFBundleVersion $NEW_BUILD" "$PLIST_PATH"
          echo "Updated build number from $CURRENT_BUILD to $NEW_BUILD"

      - name: Build IPA (Robust)
        script: |
          export NSUnbufferedIO=YES
          echo "=== ARCHIVING APP ==="
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath "$HOME/build/App.xcarchive" \
                     -allowProvisioningUpdates \
                     -destination 'generic/platform=iOS' \
                     DEVELOPMENT_TEAM="$TEAM_ID" \
                     PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
                     CODE_SIGN_STYLE="Manual" \
                     CODE_SIGN_IDENTITY="iPhone Distribution" \
                     PROVISIONING_PROFILE="$PROFILE_UUID" \
                     OTHER_CODE_SIGN_FLAGS="--keychain build.keychain" \
                     ENABLE_BITCODE=NO \
                     BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
                     EMBEDDED_CONTENT_CONTAINS_SWIFT=YES \
                     ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES \
                     LD_RUNPATH_SEARCH_PATHS="@executable_path/Frameworks" \
                     archive | tee "$HOME/build/archive_log.txt"
          echo "=== EXPORTING IPA ==="
          xcodebuild -exportArchive \
                     -archivePath "$HOME/build/App.xcarchive" \
                     -exportPath "$HOME/build/ipa" \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates | tee "$HOME/build/export_log.txt"

      - name: Validate Bundle (Comprehensive)
        script: |
          APP_PATH="$HOME/build/App.xcarchive/Products/Applications/App.app"
          WEB_ASSET_PATH="$APP_PATH/public"
          if [ ! -d "$WEB_ASSET_PATH" ]; then
            echo "❌ Web assets missing from $WEB_ASSET_PATH"
            echo "App bundle contents:"
            find "$APP_PATH" -maxdepth 2
            exit 1
          fi
          WEB_FILES=("index.html" "main.*.js" "runtime.*.js" "styles.*.css" "polyfills.*.js")
          for pattern in "${WEB_FILES[@]}"; do
            if ! compgen -G "$WEB_ASSET_PATH/$pattern" > /dev/null; then
              echo "❌ Missing web file pattern: $WEB_ASSET_PATH/$pattern"
              exit 1
            fi
          done
          FRAMEWORK_PATH="$APP_PATH/Frameworks"
          REQUIRED_PLUGINS=("Capacitor.framework" "CapacitorCordova.framework" "CapacitorCamera.framework" "CapacitorApp.framework" "CapacitorBrowser.framework" "CapacitorDevice.framework" "CapacitorFilesystem.framework" "CapacitorHaptics.framework" "CapacitorKeyboard.framework" "CapacitorNetwork.framework" "CapacitorPushNotifications.framework" "CapacitorSplashScreen.framework" "CapacitorStatusBar.framework")
          if [ ! -d "$FRAMEWORK_PATH" ]; then
            echo "❌ Frameworks directory missing in app bundle"
            echo "Bundle contents:"
            find "$APP_PATH" -maxdepth 2
            exit 1
          fi
          for plugin in "${REQUIRED_PLUGINS[@]}"; do
            if [ ! -d "$FRAMEWORK_PATH/$plugin" ]; then
              echo "❌ Missing plugin framework: $plugin"
              ls -la "$FRAMEWORK_PATH" || echo "No frameworks found"
              exit 1
            fi
          done
          if [ ! -f "$APP_PATH/Base.lproj/LaunchScreen.storyboardc" ]; then
            echo "❌ Missing compiled splash screen"
            echo "Launch assets:"
            find "$APP_PATH" -name "*.storyboard*"
            exit 1
          fi
          # Add these checks to the beginning of your script
          echo "=== CAPACITOR BRIDGE VERIFICATION ==="
          if ! grep -q "capacitor" "$APP_PATH/public/index.html"; then
            echo "❌ Capacitor not injected in index.html"
            exit 1
          fi

          # Add to your existing framework checks
          CAPACITOR_PLUGIN_FILES=(
            "$FRAMEWORK_PATH/Capacitor.framework/Capacitor"
            "$FRAMEWORK_PATH/CapacitorCordova.framework/CapacitorCordova"
          )
          for file in "${CAPACITOR_PLUGIN_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing compiled plugin: $file"
              exit 1
            fi
          done
          echo "✅ Bundle validated successfully"

      - name: Final Verification
        script: |
          echo "=== FINAL BUILD VALIDATION ==="
          APP_PATH="$HOME/build/App.xcarchive/Products/Applications/App.app"
          echo "App Version: $(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$APP_PATH/Info.plist")"
          echo "Build Version: $(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$APP_PATH/Info.plist")"
          echo "Web Assets: $(find "$APP_PATH/public" -type f | wc -l) files"
          echo "Plugin Frameworks: $(find "$APP_PATH/Frameworks" -name "*.framework" | wc -l)"
          codesign -dv --verbose=4 "$APP_PATH"
          plutil -convert xml1 "$APP_PATH/Info.plist" -o - | xmllint --format -

    artifacts:
      - $HOME/build/ipa/*.ipa
      - $HOME/build/archive_log.txt
      - $HOME/build/export_log.txt
      - build.log
      - capacitor_sync.log
      - pod_install.log
      - node_modules_list.txt
      - angular.log
      - src/environments/
    publishing:
      app_store_connect:
        auth: integration
        api_key: Codemagic-key
        submit_to_testflight: true