workflows:
  ios-distribute:
    name: iOS Distribute Workflow
    integrations:
      app_store_connect: Codemagic-key
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "papricut.app.mobile"
        TEAM_ID: "H9A4H444G4"
      groups:
        - Papricut  
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm ci
          npm install

      - name: Clean DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build Ionic project
        script: |
          ionic build --prod
          npx cap sync ios
          npx cap update ios
          cd ios/App && pod install && cd ../..

      - name: Debug Provisioning Profile
        script: |
          mkdir -p ~/provision
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/provision/profile.mobileprovision
          security cms -D -i ~/provision/profile.mobileprovision

      - name: Install Certificate & Provisioning Profile
        script: |
          echo "$DISTRIBUTION_CERTIFICATE" | base64 --decode > certificate.p12
          echo "$CERTIFICATE_PASSWORD" | security unlock-keychain -p $CERTIFICATE_PASSWORD ~/Library/Keychains/login.keychain
          security import certificate.p12 -k ~/Library/Keychains/login.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
      - name: Build .ipa with xcodebuild (Automatic Signing)
        script: |
          echo "📦 Archiving the app..."
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath "$HOME/build/App.xcarchive" \
                     -allowProvisioningUpdates \
                     -destination 'generic/platform=iOS' \
                     DEVELOPMENT_TEAM="$TEAM_ID" \
                     archive || {
                       echo "❌ Archive failed.";
                       exit 1;
                     }

          echo "📤 Exporting the IPA..."
          xcodebuild -exportArchive \
                     -archivePath "$HOME/build/App.xcarchive" \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath "$HOME/build/ipa" || {
                       echo "❌ Export failed.";
                       exit 1;
                     }

      - name: Upload to App Store Connect
        script: |
          app-store-connect-publisher \
            submit \
            --path "$HOME/build/ipa/"*.ipa \
            --platform ios \
            --api-key Codemagic-key

    artifacts:
      - build/ipa/*.ipa
