workflows:
  ios-distribute:
    name: iOS Distribute Workflow
    environment:
      vars:
        XCODE_PROJECT: "ios/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "papricut.app.mobile"
        APP_STORE_CONNECT_USERNAME: $APP_STORE_CONNECT_USERNAME
      groups:
        - Papricut
    triggering:
      events:
        - push
    scripts:
      - name: Set up keychain and code signing
        script: |
          set -e
          echo "🔐 Setting up certificate and provisioning profile..."

          # Debug: Check if variables exist
          if [ -z "$DISTRIBUTION_CERTIFICATE" ]; then
            echo "❌ DISTRIBUTION_CERTIFICATE is missing"
            exit 1
          fi
          if [ -z "$CERTIFICATE_PASSWORD" ]; then
            echo "❌ CERTIFICATE_PASSWORD is missing"
            exit 1
          fi
          if [ -z "$PROVISIONING_PROFILE" ]; then
            echo "❌ PROVISIONING_PROFILE is missing"
            exit 1
          fi

          echo "$DISTRIBUTION_CERTIFICATE" | base64 --decode > certificate.p12 || {
            echo "❌ Failed to decode DISTRIBUTION_CERTIFICATE"
            exit 1
          }

          echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision || {
            echo "❌ Failed to decode PROVISIONING_PROFILE"
            exit 1
          }

          # Setup Keychain
          echo "🔑 Creating and unlocking keychain..."
          security create-keychain -p "" build.keychain || echo "⚠️ Keychain already exists"
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

          echo "📥 Importing .p12 certificate..."
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign || {
            echo "❌ Failed to import certificate. Check CERTIFICATE_PASSWORD or .p12 integrity."
            exit 1
          }

          echo "📋 Copying provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install dependencies
        script: |
          set -e
          echo "📦 Installing dependencies..."
          npm install -g @ionic/cli
          npm ci

      - name: Build Ionic project
        script: |
          set -e
          echo "⚙️ Building Ionic project..."
          ionic build --prod || { echo "❌ Ionic build failed"; exit 1; }
          npx cap sync ios || { echo "❌ Capacitor sync failed"; exit 1; }

      - name: Build .ipa with xcodebuild
        script: |
          set -e
          echo "📱 Archiving project with xcodebuild..."
          xcodebuild -workspace ios/App.xcworkspace \
                     -scheme "$XCODE_SCHEME" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $HOME/build/App.xcarchive \
                     archive || { echo "❌ xcodebuild archive failed"; exit 1; }

          echo "📦 Exporting .ipa..."
          xcodebuild -exportArchive \
                     -archivePath $HOME/build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $HOME/build/ipa || { echo "❌ xcodebuild export failed"; exit 1; }

      - name: Upload to App Store
        script: |
          set -e
          echo "🚀 Uploading to App Store..."

          IPA_PATH=$(find $HOME/build/ipa -name "*.ipa" | head -n 1)
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ .ipa file not found. Upload aborted."
            exit 1
          fi

          if [ -z "$APP_STORE_CONNECT_USERNAME" ] || [ -z "$APP_SPECIFIC_PASSWORD" ]; then
            echo "❌ Missing App Store Connect credentials"
            exit 1
          fi

          xcrun altool --upload-app -f "$IPA_PATH" \
                       -t ios \
                       -u "$APP_STORE_CONNECT_USERNAME" \
                       -p "$APP_SPECIFIC_PASSWORD" || {
            echo "❌ Upload to App Store failed"
            exit 1
          }

    artifacts:
      - build/ipa/*.ipa
